// Pokemon
export const FETCH_ALL_POKEMON = 'FETCH_ALL_POKEMON';
export const FETCH_ONE_POKEMON = 'FETCH_ONE_POKEMON';
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON';
export const SAVE_NEXT_URL = 'SAVE_NEXT_URL';
export const SAVE_POKE_COUNT = 'SAVE_POKE_COUNT';
export const SET_POKEMON_TYPES = 'SET_POKEMON_TYPES';
// Auth
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';